Added checking within jungledisk-restart for jungeldiskserver or mysecurebackupserver

diff --git a/jungledisk-check b/jungledisk-check
--- a/jungledisk-check
+++ b/jungledisk-check
@@ -1,12 +1,12 @@
 #!/bin/sh
 
 if [ -f "/usr/local/bin/junglediskserver" ]; then
-bin_name="junglediskserver"
+	bin_name="junglediskserver"
 elif [ -f "/usr/local/bin/mysecurebackupserver" ]; then
-bin_name="mysecurebackupserver"
+	bin_name="mysecurebackupserver"
 else
-echo "Can't find Jungledisk, is it installed correctly?"
-exit 1
+	echo "Can't find Jungledisk, is it installed correctly?"
+	exit 1
 fi
 
 process=`ps auxwww | grep $bin_name | awk '{print $11}'`
diff --git a/jungledisk-restart b/jungledisk-restart
--- a/jungledisk-restart
+++ b/jungledisk-restart
@@ -1,3 +1,12 @@
 #!/bin/sh
-/etc/init.d/junglediskserver restart
+if [ -f "/usr/local/bin/junglediskserver" ]; then
+	bin_name="junglediskserver"
+elif [ -f "/usr/local/bin/mysecurebackupserver" ]; then
+	bin_name="mysecurebackupserver"
+else
+	echo "Can't find Jungledisk, is it installed correctly?"
+	exit 1
+fi
+
+/etc/init.d/$bin_name restart
 
